sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2 
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/ebooklib.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git

- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt
- asciidoctor -a toc,idprefix=xx_,version=$VERSION -b xhtml5 -T ./asciidoctor-htmlbook/htmlbook-autogen/
  -d book book.asciidoc -o book.html
- git clone https://github.com/gitenberg-dev/HTMLBook

# make book.html available to jinja2 environment by putting it into templates
- cp book.html asciidoctor-htmlbook/gitberg-machine/templates/

- /usr/bin/python asciidoctor-htmlbook/gitberg-machine/machine.py -o . -m metadata.yaml book.html
- xsltproc -stringparam external.assets.list " " ./HTMLBook/htmlbook-xsl/epub.xsl book.html
- cp ./HTMLBook/stylesheets/epub/epub.css OEBPS
- if [ -e cover.jpg ]; then cp cover.jpg OEBPS/cover.jpg; fi
# look for first images directory and one found, copy over to ./OEBPS
- find . -name images -type d | head -n 1 | xargs -I {} mv {} ./OEBPS/
- zip -rX book.epub mimetype
- zip -rX book.epub OEBPS/ META-INF/
- if test -d "OEBPS/images/"; then zip -rX book.epub OEBPS/images/ ;fi
- mv book.epub Washington-Square.epub
- ebook-convert Washington-Square.epub Washington-Square.mobi
- xvfb-run ebook-convert Washington-Square.epub Washington-Square.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: owzTc84NIap3k49+RbhyQh3GfbWv1Mn8VRYkxPksjGYWcwkRfzjuHzRZJ6SO3CAK8TcZklkdrutNrEfNxfc3mhY9Jiymf8tuVup44bsMkf8A9oGl98byYNXg6o6FjDawcEuDE6EEYiig4f3Ohizq/bwBMoKKiBdBhARVYPkjgedhkLMExiT2za7I1Ny5eaYQHpL16Un2Nolkq/MDKDt0pMlOvrOcj2gS+kCidI2nsTs/mQR3+Vg9nK3rW4s/rl5Z0t/wDlPqhWVyjSds3NAfjUvdjMxPFNKys86kSmLRS/hIRLuez1bU6WqgIOqbWAN+E5sEMlQNh8d9p4e7e37Cv6gAXmzsrLchYIQiBL67kgd5gXlyY2QO/b+CTE1TY38YmdKAlDF4opDEpFAdrj9v7jl5Rj94r+/kCa52R0gzgBeJu0XFjdsVvJ4RDJlRT2emhYYPe5WQMLf/BgL4AZfdyaAI+24mRWs1QEf4JaXIflGmEgf33Zx6Z5+qs//ZJQUOa6YeMfIGoOxvrSf/wzWDnjexBo4xZYVQy4TzVxkEoGm1GM13pWQUuYEDk0bcmOxDuuutxcCPySu5/VNE7WIO8PuF4pcCdcGCYuZENnRqp9btacVQoQL6IApeTuLRGjFyZGuNj/fnp7SSBCeh7qS2mBehMWwkuuS3LWp1KxFXV/0=
  file:
    - Washington-Square.epub
    - Washington-Square.mobi
    - Washington-Square.pdf
  "on":
    repo: GITenberg/Washington-Square_2870
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre